# Assignment 1

-  Read a matrix A from a csv file and a vector b from another csv file.
-  Perform LU decomposition for square matrix.
-  Solve the equation Ax=b and check whether there are 0,1 or infinitely many solutions.
-  Do the diagonalization of a matrix (assume it is symmetric).
-  Give exponential, sine and sigmoid functions on A.
-  Find all the eigenpairs of A.

***
<br>

## Reading matrices A and b from csv files

In [1]:
#importing numpy and pandas
import numpy as np
import pandas as pd

In [2]:
A = np.genfromtxt("sample csv matrix.csv", delimiter=',')
print("Matrix A :\n", A)

Matrix A :
 [[ 2.  0.  0.]
 [ 3. -2.  1.]
 [ 1.  0.  1.]]


In [3]:
b = np.genfromtxt("B matrix.csv", delimiter=',')
print("Vector b is :\n", b)

Vector b is :
 [ 2.  5. -3.]


<br>

## LU Decomposition

In [4]:
# importing linalg from scipy
import scipy.linalg as la

<div class="alert alert-block alert-info">
<b> LU Decomposition  </b> 
    <br>
     In LU deecpomposition, L is Lowertriangular and U is Uppertriangular
</div>

In [5]:
# LU Decomposition
P, L, U = la.lu(A)

In [6]:
P

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [7]:
L

array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.5       , 1.        ]])

In [8]:
U

array([[ 3.        , -2.        ,  1.        ],
       [ 0.        ,  1.33333333, -0.66666667],
       [ 0.        ,  0.        ,  1.        ]])

In [9]:
np.dot(L,U)

array([[ 3., -2.,  1.],
       [ 2.,  0.,  0.],
       [ 1.,  0.,  1.]])

In [10]:
S = np.dot(P, L)

In [11]:
# When we take product of P, L and U, we get the original matrix that we decomposed earlier.
np.dot(S, U)

array([[ 2.,  0.,  0.],
       [ 3., -2.,  1.],
       [ 1.,  0.,  1.]])

<br>

## Solving the system of linear equations

### Checking the number of solutions

In [12]:
rankA=np.linalg.matrix_rank(A)

aug_matrix=np.column_stack((A,b))

rank_aug_m=np.linalg.matrix_rank(aug_matrix)

if (rankA==rank_aug_m) and (rank_aug_m==np.shape(A)[0]):
    print("The system of equations has a unique solution.")
    
elif (rankA==rank_aug_m) and (rank_aug_m< np.shape(A)[0]):
    print("The system of equations has infinitely many solutions.")
    
if(rankA < rank_aug_m):
    print(" The system of equations is inconsistent.")

The system of equations has a unique solution.


### Solving the equations

In [13]:
# Solving the equation Ax=b
x = la.solve(A,b)

print("The solution is : \n",x)

The solution is : 
 [ 1. -3. -4.]


<br>

<br>

## Diagonalization

In [14]:
from sympy import *

In [15]:
M = Matrix([[2, 0, 0], [3, -2, 1], [1, 0, 1]])
M

Matrix([
[2,  0, 0],
[3, -2, 1],
[1,  0, 1]])

In [16]:
# Diagonalizing the matrix
S, D = M.diagonalize()

In [17]:
S

Matrix([
[0, 0, 1],
[1, 1, 1],
[0, 3, 1]])

In [18]:
D

Matrix([
[-2, 0, 0],
[ 0, 1, 0],
[ 0, 0, 2]])

<div class="alert alert-block alert-info">
To check if we have successfully diagonalized the matrix, we can take the product of SDS<sup>-1</sup> and it should be equal to the original matrix.
</div>

In [19]:
# coparison of the above product and original matrix
Product = S*D*S**(-1)

if S*D*S**-1==M:
    print("Successfully diagonalized")


Successfully diagonalized


<br>

## Exponential, Sine and Sigmoid functions on A

In [20]:
# Exponential function
expA = np.exp(A)
print(expA)

[[ 7.3890561   1.          1.        ]
 [20.08553692  0.13533528  2.71828183]
 [ 2.71828183  1.          2.71828183]]


In [21]:
# Sine function
SinA = np.sin(A)
print("Sine of A : \n",SinA)

Sine of A : 
 [[ 0.90929743  0.          0.        ]
 [ 0.14112001 -0.90929743  0.84147098]
 [ 0.84147098  0.          0.84147098]]


In [22]:
# Sigmoid Function
def sigmoid(X):
    return 1.0/(1.0 + np.exp(-X))

SigA = sigmoid(A)

print("Sigmoid function of A :\n",SigA)

Sigmoid function of A :
 [[0.88079708 0.5        0.5       ]
 [0.95257413 0.11920292 0.73105858]
 [0.73105858 0.5        0.73105858]]


<br>

## Eigen values and Eigen vector

In [23]:
# Calculating Eigen values and Eigen vectors

evalues, evectors = la.eig(A)

print("Eigen values : \n",evalues)
print()
print("Eigen vector : \n",evectors)

Eigen values : 
 [-2.+0.j  1.+0.j  2.+0.j]

Eigen vector : 
 [[0.         0.         0.57735027]
 [1.         0.31622777 0.57735027]
 [0.         0.9486833  0.57735027]]
